services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - .:/app
    command: bash -c "cargo watch -x run"
    ports:
      - 8000:8000

  redis:
    image: redis:7.0.11
    ports:
      - 6379
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local
